
// This file has been generated by the GUI designer. Do not modify.
namespace ss_backend_assess
{
	public partial class frmCheckOrderStatus
	{
		public virtual void Build ()
		{
			// Action group ss_backend_assess.frmCheckOrderStatus
		}
	}
}
