
// This file has been generated by the GUI designer. Do not modify.
namespace ss_backend_assess
{
	public partial class frmPaymentRequest
	{
		private global::Gtk.VBox vbox12;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview3;
		
		private global::Gtk.Label GtkLabel;
		
		private global::Gtk.VBox vbox13;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.HBox hbox18;
		
		private global::Gtk.Image image1;
		
		private global::Gtk.Button btnProofUpload;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.Button btnFinalize;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ss_backend_assess.frmPaymentRequest
			this.Name = "ss_backend_assess.frmPaymentRequest";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmPaymentRequest");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ss_backend_assess.frmPaymentRequest.Gtk.Container+ContainerChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Payment Method");
			this.vbox12.Add (this.label17);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.label17]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView ();
			this.textview3.Buffer.Text = "Total Payment Amount: - IDR\nPlease do Bank Transfer on:\n14151231512315123\na.n. Test Test Test";
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.textview3.Editable = false;
			this.GtkScrolledWindow.Add (this.textview3);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Payment Detail</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel;
			this.vbox12.Add (this.frame1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.frame1]));
			w5.Position = 1;
			// Container child vbox12.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.hbox18.Add (this.image1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.image1]));
			w6.Position = 0;
			w6.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.btnProofUpload = new global::Gtk.Button ();
			this.btnProofUpload.CanFocus = true;
			this.btnProofUpload.Name = "btnProofUpload";
			this.btnProofUpload.UseUnderline = true;
			this.btnProofUpload.Label = global::Mono.Unix.Catalog.GetString ("Upload");
			this.hbox18.Add (this.btnProofUpload);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.btnProofUpload]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.GtkAlignment1.Add (this.hbox18);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Payment Proof</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel2;
			this.vbox13.Add (this.frame2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.frame2]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.btnFinalize = new global::Gtk.Button ();
			this.btnFinalize.CanFocus = true;
			this.btnFinalize.Name = "btnFinalize";
			this.btnFinalize.UseUnderline = true;
			this.btnFinalize.Label = global::Mono.Unix.Catalog.GetString ("Finalize Order!");
			this.vbox13.Add (this.btnFinalize);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.btnFinalize]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox12.Add (this.vbox13);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.vbox13]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.Add (this.vbox12);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
