
// This file has been generated by the GUI designer. Do not modify.
namespace ss_backend_assess
{
	public partial class frmCheckOrderStats
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView nodeOrderStatus;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Entry txtShipID;
		
		private global::Gtk.Button btnCheckShipStatus;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label lblShipStatus;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ss_backend_assess.frmCheckOrderStats
			this.Name = "ss_backend_assess.frmCheckOrderStats";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmCheckOrderStatus");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ss_backend_assess.frmCheckOrderStats.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Order Status");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeOrderStatus = new global::Gtk.NodeView ();
			this.nodeOrderStatus.CanFocus = true;
			this.nodeOrderStatus.Name = "nodeOrderStatus";
			this.GtkScrolledWindow.Add (this.nodeOrderStatus);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter Shipping ID:");
			this.vbox1.Add (this.label10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label10]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.txtShipID = new global::Gtk.Entry ();
			this.txtShipID.CanFocus = true;
			this.txtShipID.Name = "txtShipID";
			this.txtShipID.IsEditable = true;
			this.txtShipID.InvisibleChar = '•';
			this.vbox1.Add (this.txtShipID);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.txtShipID]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnCheckShipStatus = new global::Gtk.Button ();
			this.btnCheckShipStatus.CanFocus = true;
			this.btnCheckShipStatus.Name = "btnCheckShipStatus";
			this.btnCheckShipStatus.UseUnderline = true;
			this.btnCheckShipStatus.Label = global::Mono.Unix.Catalog.GetString ("Check!");
			this.vbox1.Add (this.btnCheckShipStatus);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnCheckShipStatus]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Ship Status: ");
			this.hbox2.Add (this.label12);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label12]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblShipStatus = new global::Gtk.Label ();
			this.lblShipStatus.Name = "lblShipStatus";
			this.lblShipStatus.Xalign = 0F;
			this.lblShipStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("-");
			this.hbox2.Add (this.lblShipStatus);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblShipStatus]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w9.Position = 5;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
