
// This file has been generated by the GUI designer. Do not modify.
namespace ss_backend_assess
{
	public partial class frmAdminMain
	{
		private global::Gtk.VBox vbox14;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView nodeview2;
		
		private global::Gtk.HBox hbox19;
		
		private global::Gtk.Label label19;
		
		private global::Gtk.Entry entry11;
		
		private global::Gtk.Button btnOrderCheck;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ss_backend_assess.frmAdminMain
			this.Name = "ss_backend_assess.frmAdminMain";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmAdminMain");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ss_backend_assess.frmAdminMain.Gtk.Container+ContainerChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Admin Menu");
			this.vbox14.Add (this.label18);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.label18]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview2 = new global::Gtk.NodeView ();
			this.nodeview2.CanFocus = true;
			this.nodeview2.Name = "nodeview2";
			this.GtkScrolledWindow.Add (this.nodeview2);
			this.vbox14.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Selected Order#: ");
			this.hbox19.Add (this.label19);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label19]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.entry11 = new global::Gtk.Entry ();
			this.entry11.CanFocus = true;
			this.entry11.Name = "entry11";
			this.entry11.IsEditable = true;
			this.entry11.InvisibleChar = '•';
			this.hbox19.Add (this.entry11);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.entry11]));
			w5.Position = 1;
			// Container child hbox19.Gtk.Box+BoxChild
			this.btnOrderCheck = new global::Gtk.Button ();
			this.btnOrderCheck.CanFocus = true;
			this.btnOrderCheck.Name = "btnOrderCheck";
			this.btnOrderCheck.UseUnderline = true;
			this.btnOrderCheck.Label = global::Mono.Unix.Catalog.GetString ("Order Check");
			this.hbox19.Add (this.btnOrderCheck);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.btnOrderCheck]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox14.Add (this.hbox19);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox19]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.vbox14);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
